using HotelManagement.WinForms.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HotelManagement.WinForms.Reports;

// Guest folio rendered to PDF via QuestPDF. Mirrors the on-screen layout
// in CheckoutForm so the printed copy and the screen copy stay aligned.
public sealed class InvoicePdf : IDocument
{
    private const string HotelName = "Hotel Management System";
    private const string HotelTagline = "Guest Folio";

    private static readonly string PrimaryNavy = Colors.Blue.Darken4;
    private static readonly string AccentGold  = "#D4AF37";

    private readonly Invoice _invoice;

    public InvoicePdf(Invoice invoice)
    {
        _invoice = invoice;
    }

    public static void Save(Invoice invoice, string filePath)
    {
        Document.Create(new InvoicePdf(invoice).Compose).GeneratePdf(filePath);
    }

    public DocumentMetadata GetMetadata() => new()
    {
        Title  = $"Invoice {_invoice.InvoiceNumber}",
        Author = HotelName,
        Subject = $"Guest folio for {_invoice.Guest.Name}",
    };

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);
            page.PageColor(Colors.White);
            page.DefaultTextStyle(t => t.FontFamily(Fonts.SegoeUI).FontSize(10));

            page.Header().Element(ComposeHeader);
            page.Content().Element(ComposeContent);
            page.Footer().AlignCenter().Text(t =>
            {
                t.Span("Thank you for staying with us. ").FontColor(Colors.Grey.Darken1);
                t.Span("Generated by ").FontColor(Colors.Grey.Darken1);
                t.Span(HotelName).SemiBold().FontColor(PrimaryNavy);
            });
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(col =>
            {
                col.Item().Text(HotelName).FontSize(20).SemiBold().FontColor(PrimaryNavy);
                col.Item().Text(HotelTagline).FontSize(10).FontColor(Colors.Grey.Darken1);
            });

            row.ConstantItem(180).AlignRight().Column(col =>
            {
                col.Item().AlignRight().Text(_invoice.InvoiceNumber)
                    .FontSize(18).SemiBold().FontColor(AccentGold);
                col.Item().AlignRight().Text($"Date: {_invoice.InvoiceDate:MMM dd, yyyy}")
                    .FontSize(9).FontColor(Colors.Grey.Darken1);
                col.Item().AlignRight().Text($"Status: {_invoice.PaymentStatus}")
                    .FontSize(10).SemiBold().FontColor(StatusColor(_invoice.PaymentStatus));
            });
        });
    }

    private void ComposeContent(IContainer container)
    {
        container.PaddingVertical(20).Column(col =>
        {
            col.Spacing(12);

            // Guest + stay block
            col.Item().Background(Colors.Grey.Lighten4).Padding(12).Column(c =>
            {
                c.Item().Text(t =>
                {
                    t.Span(_invoice.Guest.Name).FontSize(13).SemiBold().FontColor(PrimaryNavy);
                    if (_invoice.Guest.IsVip)
                        t.Span("   VIP").FontSize(9).SemiBold().FontColor(AccentGold);
                });
                c.Item().Text($"Passport: {_invoice.Guest.Passport}").FontSize(9).FontColor(Colors.Grey.Darken2);

                var checkIn  = _invoice.Stay.CheckInDate;
                var checkOut = _invoice.Stay.ActualCheckOut ?? _invoice.Stay.ExpectedCheckOut;
                c.Item().Text(
                    $"Room {_invoice.Room.Number} ({_invoice.Room.Type})   |   " +
                    $"{checkIn:MMM dd, yyyy} → {checkOut:MMM dd, yyyy}")
                    .FontSize(10).FontColor(Colors.Grey.Darken2);
            });

            // Line items table
            col.Item().Element(ComposeLines);

            // Totals
            col.Item().AlignRight().Column(totals =>
            {
                totals.Item().Element(c => TotalRow(c, "Subtotal", _invoice.Subtotal, bold: false));
                totals.Item().Element(c => TotalRow(c, "Tax (10%)", _invoice.Tax, bold: false));
                totals.Item().LineHorizontal(1.5f).LineColor(PrimaryNavy);
                totals.Item().Element(c => TotalRow(c, "TOTAL", _invoice.Total, bold: true));
            });

            // Payment block (if paid)
            if (_invoice.PaymentMethod.HasValue && _invoice.PaymentDate.HasValue)
            {
                col.Item().PaddingTop(8).Text(
                    $"Paid via {_invoice.PaymentMethod} on {_invoice.PaymentDate:MMM dd, yyyy}")
                    .FontSize(10).SemiBold().FontColor(StatusColor(_invoice.PaymentStatus));
            }
        });
    }

    private void ComposeLines(IContainer container)
    {
        container.Column(col =>
        {
            var sections = new[]
            {
                ("Room charges",       InvoiceLineCategory.RoomCharge),
                ("Restaurant charges", InvoiceLineCategory.RestaurantCharge),
            };

            foreach (var (label, category) in sections)
            {
                var lines = _invoice.Lines.Where(l => l.Category == category).ToList();
                if (lines.Count == 0) continue;

                col.Item().PaddingTop(8).Text(label.ToUpperInvariant())
                    .FontSize(11).SemiBold().FontColor(PrimaryNavy);

                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(c =>
                    {
                        c.RelativeColumn(6);   // description
                        c.RelativeColumn(1);   // qty
                        c.RelativeColumn(2);   // unit
                        c.RelativeColumn(2);   // line total
                    });

                    table.Header(h =>
                    {
                        h.Cell().Element(HeaderCell).Text("Description");
                        h.Cell().Element(HeaderCell).AlignCenter().Text("Qty");
                        h.Cell().Element(HeaderCell).AlignRight().Text("Unit");
                        h.Cell().Element(HeaderCell).AlignRight().Text("Amount");
                    });

                    foreach (var line in lines)
                    {
                        table.Cell().Element(BodyCell).Text(line.Description);
                        table.Cell().Element(BodyCell).AlignCenter().Text(line.Quantity.ToString());
                        table.Cell().Element(BodyCell).AlignRight().Text($"${line.UnitPrice:F2}");
                        table.Cell().Element(BodyCell).AlignRight().Text($"${line.LineTotal:F2}");
                    }
                });
            }
        });
    }

    private static IContainer HeaderCell(IContainer c) =>
        c.DefaultTextStyle(t => t.SemiBold().FontColor(Colors.White))
         .Background(PrimaryNavy)
         .Padding(6);

    private static IContainer BodyCell(IContainer c) =>
        c.BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6);

    private static void TotalRow(IContainer container, string label, decimal amount, bool bold)
    {
        container.PaddingVertical(2).Row(row =>
        {
            row.ConstantItem(120).AlignRight().Text(label)
                .FontSize(bold ? 14 : 11)
                .SemiBold()
                .FontColor(bold ? PrimaryNavy : Colors.Grey.Darken2);

            row.ConstantItem(100).AlignRight().Text($"${amount:F2}")
                .FontSize(bold ? 14 : 11)
                .SemiBold()
                .FontColor(bold ? AccentGold : Colors.Grey.Darken3);
        });
    }

    private static string StatusColor(PaymentStatus status) => status switch
    {
        PaymentStatus.Paid     => Colors.Green.Darken2,
        PaymentStatus.Refunded => Colors.Orange.Darken2,
        _                      => Colors.Red.Darken2,
    };
}
